language: cpp

sudo: required

services:
- docker

env:
  matrix:
    - MPI=OFF
    - MPI=ON

script:
  - cp -vr docker ${HOME}/docker
  - cd ../../
  - mv -v ${TRAVIS_REPO_SLUG} $HOME/docker
  - docker build --build-arg MPI=${MPI}
                 -t ${TRAVIS_REPO_SLUG}:latest ${HOME}/docker/
